[projects]

  [projects.default]

  contents = [
    "introduction",
    "personal_learning_system",
    "grant_writing",
    "references"
  ]

  # Prefix for GitHub Pages.
  online_url_prefix = "/ResearchBook"

  # Port used by serve().
  port = 8000

  # Syntax highlighting.
  highlight = true
